version: '3.8'

services:
  app:
    container_name: node-express-app
    build: .
    ports:
      - "3000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start
    networks:
      - app-network